### PR TITLE
Relax version constraints for Torch, Torchvision, and Pytest dependencies

### PR DESCRIPTION
**Pull request by abhi-glitchhg**

### CODE REVIEW

**Comment by NeelayS** [comment]
I guess we can do this for all packages. What do you think?

**Comment by abhi-glitchhg** [comment]
> I guess we can do this for all packages. What do you think?

I did not do it for all other libraries because if some library scraps any feature used in the Vformer, then it might be an issue;  That's my concern. 

But *Not* blocking from my side.

**Comment by NeelayS** [comment]
Yeah, that's true. But I think we can do it for all major packages. So apart from torch and torchvision, could you make the changes for Pytest and OpenCV as well? Then we can merge this.

**Comment by NeelayS** [comment]
By the way, I think we can remove OpenCV from the requirements. It's only there because it is being used in the example script for visualization. I don't think we need to have it as a dependency for the package. So, I guess you can just make the change for Pytest and then we can merge this.

**Comment by abhi-glitchhg** [comment]
> Actually, I think we can remove OpenCV from the requirements. It's only there because it is being used in the example script for visualization. I don't think we need to have it as a dependency for the package. So, I guess you can just make the change for Pytest and then we can merge this.

yeah, I agree!  I had thought about removing OpenCV as a dependency, we can plot with matplotlib.

**Comment by abhi-glitchhg** [comment]
> Yeah, that's true. But I think we can do it for all major packages. So apart from torch and torchvision, could you make the changes for Pytest and OpenCV as well? Then we can merge this.

agree.  👍

**Review by NeelayS — APPROVED** [review]

**Pull request merged**
