### PR TITLE
Remove _Projection class 

### PR DESCRIPTION
**Pull request by abhi-glitchhg**
We can replace _Projection class with a one-liner if-else statement. 

Should we replace it with if-else or should we keep the current implementation? 

cc: @NeelayS  @aditya-agrawal-30502 @alvanli

### CODE REVIEW

**Comment by NeelayS** [comment]
@aditya-agrawal-30502 You had worked on this implementation, right? Were there any reasons behind making a class?

**Comment by aditya-agrawal-30502** [comment]
It was just that i needed a linear projection and had to use it a couple times so made a class of it.
There was no implementation of it before so hence needed

**Comment by NeelayS** [comment]
I see. Since it's only a couple of times, we can remove it I guess. What you think, @abhi-glitchhg?

**Comment by abhi-glitchhg** [comment]
> I see. Since it's only a couple of times, we can remove it I guess. What you think, @abhi-glitchhg?

yes,

**Comment by NeelayS** [comment]
Cool, merging.

**Pull request merged**
