### PR TITLE
Add memory efficient attention 

### LINKED ISSUE #74: [Paper] Self-attention Does Not Need O(n2) Memory
https://arxiv.org/abs/2112.05682

### PR DESCRIPTION
**Pull request by alvanli**

### CODE REVIEW

**Comment by alvanli** [comment]
oop that's a lot of fails, I will fix them

**Comment by abhi-glitchhg** [comment]
Fixes #74

**Comment by NeelayS** [comment]
Looks pretty good @alvanli.
Could you please also -
- Add a docs entry for this in the `docs/api` directory?
- Add the paper and code reference links to the README?

**Review by NeelayS — CHANGES_REQUESTED** [review]

**Comment by NeelayS** [comment]
Merging. Thanks @alvanli!

**Pull request merged**
